---
title: "p8105_hw2_kp3127"
output: html_document
date: "2025-09-25"
---

```{r setup}
library(tidyverse)
```

## Promblem 1
data in pols-month.csv
```{r}
pols_df=read.csv("./fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(
    col = mon, 
    into = c("year", "month", "day"), 
    sep = "-", 
  ) %>% 
    mutate(
      month=month.name[as.numeric(month)],
      president = case_when(prez_gop == 1 ~ "gop",prez_dem == 1 ~ "dem")
  ) %>% 
  select(-day, -prez_gop, -prez_dem)
```

data in snp.csv
```{r}
snp_df=read.csv("./fivethirtyeight_datasets/snp.csv") %>% 
  janitor::clean_names() %>% 
    separate(
    col = date, 
    into = c("year", "month", "day"), 
    sep = "/", 
  ) %>% 
  mutate(month=month.name[as.numeric(month)]) %>% 
  arrange(year,month) %>% 
  select(-day)
```
data in unemployment .csv
```{r}
unemp_df=read.csv("./fivethirtyeight_datasets/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = 'month',
    values_to = "unemployment"
  )
```
joining datasets
```{r}
pols_snp <- left_join(pols_df, snp_df, by = c("year", "month"))

# 再把 unemp 加进去
final_df <- left_join(pols_snp, unemp_df, by = c("year", "month"))
```

